services:
  mc:
    image: itzg/minecraft-server
    restart: unless-stopped
    environment:
      EULA: "true"
      TYPE: "FABRIC"
      ONLINE_MODE: "false"
      DIFFICULTY: "normal"
      MAX_PLAYERS: 50
      INIT_MEMORY: "2G"
      MAX_MEMORY: "8G"
      PLUGINS: |
        https://cdn.modrinth.com/data/P7dR8mSH/versions/i5tSkVBH/fabric-api-0.141.3%2B1.21.11.jar
        https://cdn.modrinth.com/data/Ha28R6CL/versions/ViT4gucI/fabric-language-kotlin-1.13.9%2Bkotlin.2.3.10.jar
        https://cdn.modrinth.com/data/aTaCgKLW/versions/tgYliGAU/silk-all-1.11.5.jar
        https://cdn.modrinth.com/data/OhduvhIc/versions/SMDUhqTN/veinminer-fabric-2.5.2.jar
        https://cdn.modrinth.com/data/gvQqBUqZ/versions/qvNsoO3l/lithium-fabric-0.21.3%2Bmc1.21.11.jar
        https://cdn.modrinth.com/data/pL3tkgTC/versions/it5JBxuL/Pl3xMarkers-0.6.6%2B1.21.11.jar
        https://cdn.modrinth.com/data/rIC2XJV4/versions/2to2gfdA/ViaFabricPlus-4.4.8.jar
        https://cdn.modrinth.com/data/rIC2XJV4/versions/2to2gfdA/ViaFabricPlus-4.4.8.jar
        https://cdn.modrinth.com/data/34T8oVNY/versions/kh6fCyFq/Pl3xMap-1.21.11-541.jar
        https://cdn.modrinth.com/data/EsAfCjCV/versions/59ti1rvg/appleskin-fabric-mc1.21.11-3.0.8.jar
        https://cdn.modrinth.com/data/9eGKb6K1/versions/pFTZ8sqQ/voicechat-fabric-1.21.11-2.6.12.jar
        https://cdn.modrinth.com/data/Vebnzrzj/versions/CzCJJMuo/LuckPerms-Fabric-5.5.21.jar
        https://cdn.modrinth.com/data/TsLS8Py5/versions/nyuyjXuq/SkinsRestorer-Mod-Fabric-15.10.2.jar
        https://cdn.modrinth.com/data/yeJMtJfW/versions/bj4FBjXG/grimac-fabric-2.3.73-0a6ac7a.jar
        https://cdn.modrinth.com/data/abooMhox/versions/8mfyGsIg/treeharvester-1.21.11-9.3.jar
        https://cdn.modrinth.com/data/jrDKjZP7/versions/r95mrAaQ/InvView-1.4.19-1.21.11%2B.jar
        https://cdn.modrinth.com/data/knsf3voQ/versions/sP6KwuYa/Gravestone-Fabric-1.21.11.jar
        https://cdn.modrinth.com/data/PL5F9WAX/versions/iZvU0GH8/NoDim-1.3.0.jar
        https://cdn.modrinth.com/data/RpXNx59A/versions/363AFEd4/auth-v1.6.2.jar
        https://cdn.modrinth.com/data/VKXzIykF/versions/UOglNAYK/sit-1.21.11-29.jar
        https://cdn.modrinth.com/data/MI2DOogd/versions/dMjjSH0K/sit-datapack-1.1.jar
      SPIGET_RESOURCES: 
    ports:
      - "25565:25565"
      - "19132:19132/udp"
      - "8080:8080"
    volumes:
      - ./:/data/:z
